// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eNote.Services.Database;

#nullable disable

namespace eNote.Services.Migrations
{
    [DbContext(typeof(ENoteContext))]
    [Migration("20240807110535_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eNote.Services.Database.Adresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Broj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adresa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Broj = "12",
                            Grad = "Sarajevo",
                            Ulica = "Bistrik"
                        },
                        new
                        {
                            Id = 2,
                            Broj = "15",
                            Grad = "Sarajevo",
                            Ulica = "Maršala Tita"
                        },
                        new
                        {
                            Id = 3,
                            Broj = "8",
                            Grad = "Sarajevo",
                            Ulica = "Mula Mustafe Bašeskije"
                        },
                        new
                        {
                            Id = 4,
                            Broj = "18",
                            Grad = "Sarajevo",
                            Ulica = "Obala Kulina bana"
                        },
                        new
                        {
                            Id = 5,
                            Broj = "14",
                            Grad = "Sarajevo",
                            Ulica = "Veliki Alifakovac"
                        });
                });

            modelBuilder.Entity("eNote.Services.Database.Instrumenti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proizvodjac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SlikaThumb")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("VrstaInstrumentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("VrstaInstrumentaId");

                    b.ToTable("Instrumenti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KorisnikId = 4,
                            Model = "J-45",
                            Opis = "Ikonična akustična gitara poznata po bogatom, punom zvuku.",
                            Proizvodjac = "Gibson",
                            VrstaInstrumentaId = 1
                        },
                        new
                        {
                            Id = 2,
                            KorisnikId = 4,
                            Model = "214ce",
                            Opis = "Popularna grand auditorium akustična gitara sa svijetlim, jasnim tonom.",
                            Proizvodjac = "Taylor",
                            VrstaInstrumentaId = 1
                        },
                        new
                        {
                            Id = 3,
                            KorisnikId = 4,
                            Model = "CD-60S",
                            Opis = "Pristupačna akustična gitara savršena za početnike i srednje napredne svirače.",
                            Proizvodjac = "Fender",
                            VrstaInstrumentaId = 1
                        },
                        new
                        {
                            Id = 4,
                            KorisnikId = 4,
                            Model = "Stratocaster",
                            Opis = "Klasična električna gitara poznata po svojoj svestranosti i glatkoj svirljivosti.",
                            Proizvodjac = "Fender",
                            VrstaInstrumentaId = 1
                        },
                        new
                        {
                            Id = 5,
                            KorisnikId = 4,
                            Model = "Les Paul",
                            Opis = "Legendarna električna gitara omiljena zbog bogatog tona i održavanja.",
                            Proizvodjac = "Gibson",
                            VrstaInstrumentaId = 1
                        },
                        new
                        {
                            Id = 6,
                            KorisnikId = 4,
                            Model = "RG",
                            Opis = "Visokoperformansna električna gitara popularna među rok i metal sviračima.",
                            Proizvodjac = "Ibanez",
                            VrstaInstrumentaId = 1
                        },
                        new
                        {
                            Id = 7,
                            KorisnikId = 4,
                            Model = "Custom 24",
                            Opis = "Visokokvalitetna električna gitara poznata po svojoj prelijepoj izradi i zvuku.",
                            Proizvodjac = "PRS",
                            VrstaInstrumentaId = 1
                        },
                        new
                        {
                            Id = 8,
                            KorisnikId = 4,
                            Model = "Pacifica",
                            Opis = "Svestrana električna gitara pogodna za različite žanrove.",
                            Proizvodjac = "Yamaha",
                            VrstaInstrumentaId = 1
                        },
                        new
                        {
                            Id = 9,
                            KorisnikId = 4,
                            Model = "Dinky",
                            Opis = "Električna gitara dizajnirana za brzo sviranje i snažan zvuk.",
                            Proizvodjac = "Jackson",
                            VrstaInstrumentaId = 1
                        },
                        new
                        {
                            Id = 10,
                            KorisnikId = 4,
                            Model = "C-1",
                            Opis = "Električna gitara poznata po svojoj čvrstoj izradi i teškim tonovima.",
                            Proizvodjac = "Schecter",
                            VrstaInstrumentaId = 1
                        },
                        new
                        {
                            Id = 11,
                            KorisnikId = 4,
                            Model = "Precision Bass",
                            Opis = "Industrijski standard bas gitara poznata po dubokom, udarnom zvuku.",
                            Proizvodjac = "Fender",
                            VrstaInstrumentaId = 1
                        },
                        new
                        {
                            Id = 12,
                            KorisnikId = 4,
                            Model = "SR",
                            Opis = "Elegantna bas gitara popularna zbog svog brzog vrata i svestranih tonova.",
                            Proizvodjac = "Ibanez",
                            VrstaInstrumentaId = 1
                        },
                        new
                        {
                            Id = 13,
                            KorisnikId = 4,
                            Model = "Thunderbird",
                            Opis = "Ikonična bas gitara poznata po jedinstvenom dizajnu i snažnom zvuku.",
                            Proizvodjac = "Gibson",
                            VrstaInstrumentaId = 1
                        },
                        new
                        {
                            Id = 14,
                            KorisnikId = 4,
                            Model = "BB",
                            Opis = "Pouzdana bas gitara sa velikim balansom svirljivosti i tona.",
                            Proizvodjac = "Yamaha",
                            VrstaInstrumentaId = 1
                        },
                        new
                        {
                            Id = 15,
                            KorisnikId = 4,
                            Model = "RockBass",
                            Opis = "Bas gitara poznata po svom jedinstvenom 'growl' tonu i ergonomskoj izradi.",
                            Proizvodjac = "Warwick",
                            VrstaInstrumentaId = 1
                        },
                        new
                        {
                            Id = 16,
                            KorisnikId = 4,
                            Model = "Export",
                            Opis = "Pristupačan bubanj set savršen za početnike i srednje napredne bubnjare.",
                            Proizvodjac = "Pearl",
                            VrstaInstrumentaId = 3
                        },
                        new
                        {
                            Id = 17,
                            KorisnikId = 4,
                            Model = "Imperialstar",
                            Opis = "Svestran bubanj set sa izvrsnom izradom i zvukom.",
                            Proizvodjac = "Tama",
                            VrstaInstrumentaId = 3
                        },
                        new
                        {
                            Id = 18,
                            KorisnikId = 4,
                            Model = "Breakbeats",
                            Opis = "Kompaktni bubanj set dizajniran za prenosivost i odličan ton.",
                            Proizvodjac = "Ludwig",
                            VrstaInstrumentaId = 3
                        },
                        new
                        {
                            Id = 19,
                            KorisnikId = 4,
                            Model = "Mark VI",
                            Opis = "Legendarni saksofon poznat po izvrsnom tonu i svirljivosti.",
                            Proizvodjac = "Selmer",
                            VrstaInstrumentaId = 2
                        },
                        new
                        {
                            Id = 20,
                            KorisnikId = 4,
                            Model = "YAS-280",
                            Opis = "Popularni saksofon među studentima i srednje naprednim sviračima.",
                            Proizvodjac = "Yamaha",
                            VrstaInstrumentaId = 2
                        },
                        new
                        {
                            Id = 21,
                            KorisnikId = 4,
                            Model = "Minilogue",
                            Opis = "Analogni sintisajzer poznat po svom bogatom, toplom zvuku.",
                            Proizvodjac = "Korg",
                            VrstaInstrumentaId = 4
                        },
                        new
                        {
                            Id = 22,
                            KorisnikId = 4,
                            Model = "Juno-DS",
                            Opis = "Svestrani sintisajzer popularan za žive nastupe i studijsku upotrebu.",
                            Proizvodjac = "Roland",
                            VrstaInstrumentaId = 4
                        },
                        new
                        {
                            Id = 23,
                            KorisnikId = 4,
                            Model = "Sub Phatty",
                            Opis = "Analogni sintisajzer poznat po svom snažnom basu i lead tonovima.",
                            Proizvodjac = "Moog",
                            VrstaInstrumentaId = 4
                        },
                        new
                        {
                            Id = 24,
                            KorisnikId = 4,
                            Model = "Stradivarius",
                            Opis = "Profesionalni trombon poznat po bogatom tonu i preciznoj intonaciji.",
                            Proizvodjac = "Bach",
                            VrstaInstrumentaId = 2
                        },
                        new
                        {
                            Id = 25,
                            KorisnikId = 4,
                            Model = "YSL-354",
                            Opis = "Studentski trombon poznat po svojoj izdržljivosti i lakoći sviranja.",
                            Proizvodjac = "Yamaha",
                            VrstaInstrumentaId = 2
                        });
                });

            modelBuilder.Entity("eNote.Services.Database.IznajmljivanjeInstrumenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumIznajmljivanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumVracanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<bool>("Vracen")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("StudentId");

                    b.ToTable("IznajmljivanjeInstrumenata");
                });

            modelBuilder.Entity("eNote.Services.Database.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdresaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SlikaThumb")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdresaId");

                    b.HasIndex("UlogaId");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdresaId = 1,
                            DatumRodjenja = new DateTime(2024, 8, 7, 13, 5, 34, 878, DateTimeKind.Local).AddTicks(7292),
                            Email = "admin@outlook.com",
                            Ime = "Admin",
                            KorisnickoIme = "admin",
                            LozinkaHash = "ZkI1kU9URV5MZIBNEVSHhZxgTI2t0YfDFxsOoN8yAC0=",
                            LozinkaSalt = "FzxxZCGOpeSbzl1KWRh2nQ==",
                            Prezime = "Admin",
                            Telefon = "000000000",
                            UlogaId = 1
                        },
                        new
                        {
                            Id = 2,
                            AdresaId = 4,
                            DatumRodjenja = new DateTime(2024, 8, 7, 13, 5, 34, 878, DateTimeKind.Local).AddTicks(7342),
                            Email = "john.doe@outlook.com",
                            Ime = "John",
                            KorisnickoIme = "instruktor",
                            LozinkaHash = "uGhnS1nkRnlbGV0zHuRARDejLQhZAJfptE8OchoySWk=",
                            LozinkaSalt = "NPnpNRwx/B7lGXDm76t65A==",
                            Prezime = "Doe",
                            Telefon = "111111111",
                            UlogaId = 2
                        },
                        new
                        {
                            Id = 3,
                            AdresaId = 5,
                            DatumRodjenja = new DateTime(2024, 8, 7, 13, 5, 34, 878, DateTimeKind.Local).AddTicks(7345),
                            Email = "jane.doe@outlook.com",
                            Ime = "Jane",
                            KorisnickoIme = "ucenik",
                            LozinkaHash = "FWb3dXVmidxXQpnHIYyZgTsUiKvJqsnY38S0qlNNGXU=",
                            LozinkaSalt = "OhoavcXsFYSCK4lcxUrVAw==",
                            Prezime = "Doe",
                            Telefon = "222222222",
                            UlogaId = 3
                        },
                        new
                        {
                            Id = 4,
                            AdresaId = 2,
                            Email = "shop1@outlook.com",
                            KorisnickoIme = "shop1",
                            LozinkaHash = "Oznr28cszd7J0By2QxYLvB4ZEZUFrxsdSg7WuI5x94Q=",
                            LozinkaSalt = "i2gF+/z6F2mk553YqtdMTA==",
                            Naziv = "Bonemeal Music Shop",
                            Telefon = "333333333",
                            UlogaId = 4
                        });
                });

            modelBuilder.Entity("eNote.Services.Database.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstruktorId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstruktorId");

                    b.ToTable("Kursevi");
                });

            modelBuilder.Entity("eNote.Services.Database.Obavijest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPostavljanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PredavanjeId")
                        .HasColumnType("int");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PredavanjeId");

                    b.ToTable("Obavijesti");
                });

            modelBuilder.Entity("eNote.Services.Database.OglasnaTabla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumPostavljanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("OglasnaTabla");
                });

            modelBuilder.Entity("eNote.Services.Database.PredajaZadatka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPredaje")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Ocjena")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("ZadatakId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("ZadatakId");

                    b.ToTable("PredajaZadatka");
                });

            modelBuilder.Entity("eNote.Services.Database.Predavanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrijeme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KursId");

                    b.ToTable("Predavanja");
                });

            modelBuilder.Entity("eNote.Services.Database.Prisustvo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("PotvrdaPrisustva")
                        .HasColumnType("bit");

                    b.Property<int>("PredavanjeId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredavanjeId");

                    b.HasIndex("StudentId");

                    b.ToTable("Prisustva");
                });

            modelBuilder.Entity("eNote.Services.Database.Uloge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uloge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Instruktor"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Ucenik"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Shop"
                        });
                });

            modelBuilder.Entity("eNote.Services.Database.Upis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KursId");

                    b.HasIndex("StudentId");

                    b.ToTable("Upisi");
                });

            modelBuilder.Entity("eNote.Services.Database.VrstaInstrumenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VrstaInstrumenta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Žičani"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Limeni"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Udaraljke"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Instrument s tipkama"
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Elektronički"
                        });
                });

            modelBuilder.Entity("eNote.Services.Database.Zadatak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PredavanjeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RokPredaje")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PredavanjeId");

                    b.ToTable("Zadaci");
                });

            modelBuilder.Entity("eNote.Services.Database.Instrumenti", b =>
                {
                    b.HasOne("eNote.Services.Database.Korisnik", "MusicShop")
                        .WithMany("Instrumenti")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eNote.Services.Database.VrstaInstrumenta", "VrstaInstrumenta")
                        .WithMany("Instrumenti")
                        .HasForeignKey("VrstaInstrumentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MusicShop");

                    b.Navigation("VrstaInstrumenta");
                });

            modelBuilder.Entity("eNote.Services.Database.IznajmljivanjeInstrumenta", b =>
                {
                    b.HasOne("eNote.Services.Database.Instrumenti", "Instrument")
                        .WithMany("IznajmljivanjeInstrumenta")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eNote.Services.Database.Korisnik", "Student")
                        .WithMany("IznajmljivanjeInstrumenta")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("eNote.Services.Database.Korisnik", b =>
                {
                    b.HasOne("eNote.Services.Database.Adresa", "Adresa")
                        .WithMany("Korisnici")
                        .HasForeignKey("AdresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eNote.Services.Database.Uloge", "Uloga")
                        .WithMany("Korisnici")
                        .HasForeignKey("UlogaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adresa");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("eNote.Services.Database.Kurs", b =>
                {
                    b.HasOne("eNote.Services.Database.Korisnik", "Instruktor")
                        .WithMany("Kurs")
                        .HasForeignKey("InstruktorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instruktor");
                });

            modelBuilder.Entity("eNote.Services.Database.Obavijest", b =>
                {
                    b.HasOne("eNote.Services.Database.Predavanje", "Predavanje")
                        .WithMany("Obavijesti")
                        .HasForeignKey("PredavanjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predavanje");
                });

            modelBuilder.Entity("eNote.Services.Database.OglasnaTabla", b =>
                {
                    b.HasOne("eNote.Services.Database.Korisnik", "Autor")
                        .WithMany("PostavljeneObavijesti")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("eNote.Services.Database.PredajaZadatka", b =>
                {
                    b.HasOne("eNote.Services.Database.Korisnik", "Student")
                        .WithMany("PredajaZadatka")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eNote.Services.Database.Zadatak", "Zadatak")
                        .WithMany("PredajaZadatka")
                        .HasForeignKey("ZadatakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Zadatak");
                });

            modelBuilder.Entity("eNote.Services.Database.Predavanje", b =>
                {
                    b.HasOne("eNote.Services.Database.Kurs", "Kurs")
                        .WithMany("Predavanje")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("eNote.Services.Database.Prisustvo", b =>
                {
                    b.HasOne("eNote.Services.Database.Predavanje", "Predavanje")
                        .WithMany("Prisustvo")
                        .HasForeignKey("PredavanjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eNote.Services.Database.Korisnik", "Student")
                        .WithMany("Prisustvo")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predavanje");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("eNote.Services.Database.Upis", b =>
                {
                    b.HasOne("eNote.Services.Database.Kurs", "Kurs")
                        .WithMany("Upis")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eNote.Services.Database.Korisnik", "Student")
                        .WithMany("Upis")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("eNote.Services.Database.Zadatak", b =>
                {
                    b.HasOne("eNote.Services.Database.Predavanje", "Predavanje")
                        .WithMany("Zadaci")
                        .HasForeignKey("PredavanjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predavanje");
                });

            modelBuilder.Entity("eNote.Services.Database.Adresa", b =>
                {
                    b.Navigation("Korisnici");
                });

            modelBuilder.Entity("eNote.Services.Database.Instrumenti", b =>
                {
                    b.Navigation("IznajmljivanjeInstrumenta");
                });

            modelBuilder.Entity("eNote.Services.Database.Korisnik", b =>
                {
                    b.Navigation("Instrumenti");

                    b.Navigation("IznajmljivanjeInstrumenta");

                    b.Navigation("Kurs");

                    b.Navigation("PostavljeneObavijesti");

                    b.Navigation("PredajaZadatka");

                    b.Navigation("Prisustvo");

                    b.Navigation("Upis");
                });

            modelBuilder.Entity("eNote.Services.Database.Kurs", b =>
                {
                    b.Navigation("Predavanje");

                    b.Navigation("Upis");
                });

            modelBuilder.Entity("eNote.Services.Database.Predavanje", b =>
                {
                    b.Navigation("Obavijesti");

                    b.Navigation("Prisustvo");

                    b.Navigation("Zadaci");
                });

            modelBuilder.Entity("eNote.Services.Database.Uloge", b =>
                {
                    b.Navigation("Korisnici");
                });

            modelBuilder.Entity("eNote.Services.Database.VrstaInstrumenta", b =>
                {
                    b.Navigation("Instrumenti");
                });

            modelBuilder.Entity("eNote.Services.Database.Zadatak", b =>
                {
                    b.Navigation("PredajaZadatka");
                });
#pragma warning restore 612, 618
        }
    }
}
